# A sample Gemfile
source "https://rubygems.org"


gem "rb-fsevent"
gem "activesupport"
gem "guard-nanoc"
gem "nanoc"

gem "nutils"
gem "nanoc-cachebuster"

gem "sass"
gem "compass"
gem 'compass-blueprint'
gem 'compass-normalize'
gem "coffee-script"
gem "autoprefixer-rails"
gem "sprockets"
gem "nokogiri"
gem "oga"
gem "erubis"
gem "kramdown"
gem "coderay"
gem "builder"
gem "htmlbeautifier"

gem "pry"