# A sample Gemfile
source "https://rubygems.org"


gem "rb-fsevent"
gem 'nanoc-live'
gem "nanoc"
gem "nanoc-cachebuster", github: "ximus/nanoc-cachebuster", branch: "develop"

gem "tailwindcss-ruby"

gem "sass", require: false
gem "compass"
gem 'compass-blueprint'
gem 'compass-normalize'
gem "coffee-script"
gem "autoprefixer-rails"
gem "sprockets"
gem "nokogiri"
gem "erubis"
gem "kramdown"

gem 'pry'
