# A sample Gemfile
source "https://rubygems.org"


gem "rb-fsevent"
gem "guard-nanoc"
gem "nanoc"

gem "nutils"
gem "nanoc-cachebuster", github: "ximus/nanoc-cachebuster", branch: "develop"

gem "sass"
gem "compass"
gem 'compass-blueprint'
gem 'compass-normalize'
gem "coffee-script"
gem "autoprefixer-rails"
gem "sprockets"
gem "nokogiri"
gem "erubis"
gem "kramdown"