require 'pry'

import "../shared/tasks.rake"

task :deploy => [
  'compile:pdf_resume',
  'optimize:jpeg',
  'optimize:png',
  # 'optimize:css',
  # 'optimize:js',
]

namespace :compile do
  desc "Generates the pdf version of my resume"
  task :pdf_resume do
    require 'puppeteer-ruby'
    require 'webrick'

    Puppeteer.launch(headless: true) do |browser|
      server = WEBrick::HTTPServer.new DocumentRoot: "output", Port: 0
      Thread.new { server.start }
      page = browser.new_page
      {
        "resume/index.html" => "maxime-liron-resume.pdf",
        "resume-old/index.html" => "maxime-liron-resume-old.pdf",
      }.each do |from, to|
        page.goto("http://localhost:#{server.config[:Port]}/#{from}")
        page.pdf(path: "output/#{to}")
      end
      page.close
      server.shutdown
    end
  end
end
